const qs=(s,c=document)=>c.querySelector(s);const qsa=(s,c=document)=>[...c.querySelectorAll(s)];
const menuBtn=qs('.menu-button'),menu=qs('.site-menu'),backdrop=qs('.menu-backdrop');let lastFocus=null;
function setMenu(open){if(!menu)return;lastFocus=open?document.activeElement:lastFocus;menu.classList.toggle('open',open);backdrop?.classList.toggle('open',open);menuBtn?.classList.toggle('is-open',open);menuBtn?.setAttribute('aria-expanded',String(open));menu?.setAttribute('aria-hidden',String(!open));document.body.classList.toggle('menu-open',open);if(open)qs('.menu-close',menu)?.focus({preventScroll:true});else if(lastFocus instanceof HTMLElement)lastFocus.focus({preventScroll:true});}
menuBtn?.addEventListener('click',()=>setMenu(!menu.classList.contains('open')));qsa('[data-menu-close]').forEach(x=>x.addEventListener('click',()=>setMenu(false)));qsa('a',menu).forEach(a=>a.addEventListener('click',()=>setMenu(false)));document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(menu?.classList.contains('open'))setMenu(false);if(qs('#projectDialog')?.open)qs('#projectDialog').close();}});
qsa('[data-scroll]').forEach(btn=>btn.addEventListener('click',()=>{const t=qs(btn.dataset.scroll);setMenu(false);qs('#projectDialog')?.open&&qs('#projectDialog').close();t?.scrollIntoView({behavior:'smooth',block:'start'});}));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.1,rootMargin:'0px 0px -6%'});qsa('.reveal').forEach(el=>io.observe(el));

const projectData={
  loftline:{title:'Loftline House',image:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1800&q=84',alt:'Bright tiny house with loft and open stair',text:'A compact-home concept shaped around a clear central aisle, a loft sleeping zone and storage that disappears into the architecture.',scope:'Compact-home planning',focus:'Loft · stair · integrated storage'},
  windowhouse:{title:'Window House',image:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1800&q=84',alt:'Bright narrow home with timber details',text:'A linear-living study that keeps the long view open, places storage at the edges and uses daylight as the main visual feature.',scope:'Interior redesign',focus:'Daylight · storage · compact kitchen'},
  barnhouse:{title:'Barn House',image:'https://images.unsplash.com/photo-1615529162924-f8605388461d?auto=format&fit=crop&w=1800&q=84',alt:'Warm cottage interior with timber details',text:'A renovation concept that keeps character while simplifying the plan with warmer joinery, a sliding partition and cleaner working zones.',scope:'Cottage renovation',focus:'Kitchen · partition · warm oak'},
  gardenhouse:{title:'Garden House',image:'https://images.unsplash.com/photo-1771372578232-7c20a006f7b4?auto=format&fit=crop&w=1800&q=84',alt:'Bright modern dining room with large windows',text:'A light-led renovation study linking dining, garden views and circulation so the main floor reads as one generous room.',scope:'Ground-floor renewal',focus:'Daylight · dining flow · timber'},
  oakloft:{title:'Oak Loft',image:'https://images.unsplash.com/photo-1723810737026-afbee93dd5a5?auto=format&fit=crop&w=1800&q=84',alt:'Bright white loft with pale timber floor',text:'A calm loft interior concept where pale timber, concealed storage and quiet detailing preserve the sense of open volume.',scope:'Loft interior',focus:'Open volume · pale timber · detailing'}
};
const dialog=qs('#projectDialog');qsa('.project-open').forEach(btn=>btn.addEventListener('click',()=>{const card=btn.closest('[data-project]'),d=projectData[card?.dataset.project];if(!dialog||!d)return;qs('#dialogImage').src=d.image;qs('#dialogImage').alt=d.alt;qs('#dialogTitle').textContent=d.title;qs('#dialogText').textContent=d.text;qs('#dialogScope').textContent=d.scope;qs('#dialogFocus').textContent=d.focus;dialog.showModal();qs('.dialog-close',dialog)?.focus({preventScroll:true});}));qs('.dialog-close')?.addEventListener('click',()=>dialog.close());dialog?.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});

const form=qs('#consultationForm'),status=qs('#formStatus'),overlay=qs('#sendOverlay'),mark=qs('#sendMark'),title=qs('#sendTitle'),text=qs('#sendText');
function fieldError(f,msg=''){const el=qs(`[data-error-for="${f.name}"]`,form);if(el)el.textContent=msg;f.setAttribute('aria-invalid',String(Boolean(msg)));return !msg}
function valid(f){let m='';if(f.validity.valueMissing)m='Required.';else if(f.type==='email'&&f.validity.typeMismatch)m='Enter a valid email.';else if(f.validity.tooShort)m='Enter at least 3 characters.';return fieldError(f,m)}
qsa('[required]',form).forEach(f=>['input','change'].forEach(ev=>f.addEventListener(ev,()=>valid(f))));
function sendState(s){if(!overlay)return;overlay.classList.add('open');overlay.setAttribute('aria-hidden','false');mark.textContent=s==='sending'?'V':s==='success'?'✓':'!';title.textContent=s==='sending'?'Sending…':s==='success'?'Succeeded':'Could not send';text.textContent=s==='sending'?'Your request is being sent securely.':s==='success'?'Your consultation request was sent successfully.':'Your form has been kept. Try again.'}
function closeSend(){overlay?.classList.remove('open');overlay?.setAttribute('aria-hidden','true')}
form?.addEventListener('submit',async e=>{e.preventDefault();const req=qsa('[required]',form),bad=req.find(f=>!valid(f));if(bad){bad.focus();status.textContent='Please complete the required fields.';return}const fd=new FormData(form);if(fd.get('website'))return;const submit=qs('[type="submit"]',form);submit.disabled=true;status.textContent='';sendState('sending');const payload={name:String(fd.get('name')||'').trim(),email:String(fd.get('email')||'').trim(),project:String(fd.get('project')||'').trim(),budget:String(fd.get('budget')||'').trim(),message:String(fd.get('message')||'').trim(),requestId:crypto.randomUUID?.()||String(Date.now())};try{const res=await fetch('/api/consultation',{method:'POST',headers:{'Content-Type':'application/json','X-Request-Id':payload.requestId},body:JSON.stringify(payload)});const data=await res.json().catch(()=>({}));if(!res.ok||!data.ok)throw new Error('send');sendState('success');form.reset();status.textContent='Request sent.';setTimeout(closeSend,1800)}catch{sendState('error');status.textContent='Send failed — your details are still here.';setTimeout(closeSend,2600)}finally{submit.disabled=false}});
